import { createContext, useContext, useState, ReactNode } from "react";
import AuthService from "../services/authService";

export type Lang = "fr" | "en";

const translations = {
  en: {
    // Nav
    dashboard: "Dashboard",
    customers: "Customers",
    spAdmins: "SP Admins",
    transactions: "Transactions",
    terminals: "Terminals",
    reports: "Reports",
    reconciliation: "Reconciliation",
    endOfDay: "End of Day",
    invoices: "Invoices",

    // Common
    search: "Search",
    filter: "Filter",
    status: "Status",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    add: "Add",
    create: "Create",
    loading: "Loading...",
    noData: "No data",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    date: "Date",
    amount: "Amount",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    total: "Total",
    export: "Export",
    close: "Close",
    back: "Back",
    confirm: "Confirm",
    saving: "Saving...",
    deleting: "Deleting...",
    creating: "Creating...",
    refresh: "Refresh",
    tryAgain: "Try Again",
    clearFilters: "Clear Filters",
    viewDetails: "View Details",
    saveChanges: "Save Changes",
    exportCsv: "Export CSV",
    exportReport: "Export Report",
    show: "Show",
    hide: "Hide",
    type: "Type",
    role: "Role",
    created: "Created",
    currency: "Currency",
    online: "Online",
    offline: "Offline",
    enabled: "Enabled",
    disabled: "Disabled",

    // Dashboard
    totalRevenue: "Total Revenue",
    totalTransactions: "Total Transactions",
    successRate: "Success Rate",
    activeTerminals: "Active Terminals",
    recentActivity: "Recent Activity",
    overview: "Overview",
    paymentDashboard: "Payment Dashboard",
    welcomeBack: "Welcome back",
    hotelPaymentOverview: "Here's your hotel's payment overview.",
    todayRevenue: "Today's Revenue",
    comparedToYesterday: "Compared to yesterday",
    monthToDate: "Month to Date",
    thisMonthTotal: "This month's total",
    avgTransaction: "Avg Transaction",
    perTransaction: "Per transaction",
    failedTransactions: "Failed Transactions",
    inValue: "in value",
    revenueTrend: "Revenue Trend (Last 7 Days)",
    dailyRevenueVolume: "Daily revenue and transaction volume",
    paymentMethods: "Payment Methods",
    distributionByCard: "Distribution by card brand and digital wallets",
    performanceByLocation: "Performance by Location",
    transactionVolumeByLocation: "Transaction volume and revenue by hotel location",

    // Transactions
    reference: "Reference",
    paymentMethod: "Payment Method",
    customer: "Customer",
    fulfilled: "Fulfilled",
    failed: "Failed",
    pending: "Pending",
    refunded: "Refunded",
    transactionList: "Transaction List",
    transactionsFound: "transactions found",
    noTransactionsFound: "No transactions found",
    noTransactionsMatchFilters: "No transactions match your filters",
    loadingTransactions: "Loading transactions...",
    transactionId: "Transaction ID",
    dateTime: "Date & Time",
    allStatuses: "All statuses",
    allMethods: "All methods",

    // Terminals
    serialNumber: "Serial Number",
    location: "Location",
    model: "Model",
    lastSeen: "Last Seen",
    terminalManagement: "Terminal Management",
    monitorTerminals: "Monitor and manage all connected payment terminals",
    addTerminal: "Add Terminal",
    totalTerminals: "Total Terminals",
    acrossAllLocations: "Across all locations",
    onlineTerminals: "Online Terminals",
    currentlyActive: "Currently active",
    totalTransactionsToday: "Total Transactions Today",
    acrossAllTerminals: "Across all terminals",
    terminalsFound: "terminal(s) found",
    terminalId: "Terminal ID",
    todayTransactions: "Today's Transactions",
    terminalTodayRevenue: "Today's Revenue",
    searchTerminal: "Search by ID, name or location...",

    // Customers
    properties: "Properties",
    users: "Users",
    addCustomer: "Add Customer",
    editCustomer: "Edit Customer",
    deleteCustomer: "Delete Customer",
    manageCustomers: "Manage all customers, their properties and users",
    totalCustomers: "Total Customers",
    totalProperties: "Total Properties",
    totalUsers: "Total Users",
    customerList: "Customer List",
    customersFound: "customers found",
    noCustomersYet: "No customers yet. Create your first one!",
    noCustomersMatchFilters: "No customers match your filters.",
    searchCustomer: "Search by name or email...",
    newCustomer: "New Customer",
    createCustomer: "Create Customer",
    deleteCustomerConfirm: "Are you sure you want to delete",
    deleteCustomerWarning: "This will also delete all their properties and users. This action cannot be undone.",
    customerInformation: "Customer Information",
    addCustomerDesc: "Add a new customer to the platform",
    updateCustomerDesc: "Update customer information",

    // Customer Detail
    backToCustomers: "Back to Customers",
    addProperty: "Add Property",
    editProperty: "Edit Property",
    deleteProperty: "Delete Property",
    noPropertiesYet: "No properties yet. Add the first one!",
    addUser: "Add User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    noUsersYet: "No users yet. Add the first one!",
    propertiesRoles: "Properties & Roles",
    selectPropertiesDesc: "Select properties this user can access and set their role for each.",
    noPropertiesForUser: "No properties yet. Add a property first.",
    fullName: "Full Name",
    temporaryPassword: "Temporary password",
    passwordMinChars: "Password * (min 8 chars)",

    // Auth
    login: "Sign In",
    logout: "Sign Out",
    password: "Password",
    forgotPassword: "Forgot password?",
    mfaWarning: "MFA is disabled on your account. Enable it for better security.",
    enableMfa: "Enable MFA",
    backToSignIn: "Back to Sign In",
    resetPassword: "Reset Password",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc: "We'll send a reset link to your email address.",
    sendResetLink: "Send Reset Link",
    sending: "Sending...",
    resetLinkSent: "If an account with that email exists, a reset link has been sent. Please check your inbox.",
    createNewPassword: "Create a new password",
    chooseStrongPassword: "Choose a strong password to secure your account.",
    resetPasswordTitle: "Reset Password",
    enterNewPasswordBelow: "Enter your new password below.",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    resetting: "Resetting...",
    passwordResetSuccess: "Your password has been reset successfully.",
    invalidResetLink: "Invalid reset link.",
    missingToken: "This link is missing a token. Please request a new password reset.",
    requestNewLink: "Request new link",
    passwordsDoNotMatch: "Passwords do not match.",
    passwordMinLength: "Password must be at least 8 characters.",
    invalidToken: "Invalid or missing reset token. Please request a new reset link.",
    resetLinkExpired: "Failed to reset password. The link may have expired.",
    editProfile: "Edit profile",
    signOut: "Sign out",

    // Profile
    profile: "Profile",
    manageAccountSettings: "Manage your account settings and preferences",
    personalInformation: "Personal Information",
    accountSettings: "Account Settings",
    changePassword: "Change Password",
    twoFactorAuth: "Two-Factor Authentication",
    notificationPreferences: "Notification Preferences",
    activitySummary: "Activity Summary",
    lastLogin: "Last Login",
    sessionsActive: "Sessions Active",
    accountStatus: "Account Status",
    currentPassword: "Current Password",
    enterCurrentPassword: "Enter current password",
    minEightChars: "Min. 8 characters",
    repeatNewPassword: "Repeat new password",
    newPasswordsNoMatch: "New passwords do not match.",
    newPasswordMinLength: "New password must be at least 8 characters.",
    passwordChanged: "Password changed",
    passwordUpdatedSuccess: "Your password has been updated successfully.",

    // MFA
    mfaTitle: "Multi-Factor Authentication",
    mfaDesc: "Protect your account with an authenticator app and one-time backup codes.",
    backToProfile: "Back to profile",
    loadingMfaStatus: "Loading MFA status...",
    currentProtection: "Current protection",
    mfaEnabled: "MFA enabled",
    mfaDisabled: "MFA disabled",
    backupCodesRemaining: "Backup codes remaining",
    enableMfaProtection: "Enable MFA protection",
    enableMfaDesc: "Add an authenticator app and backup codes to protect this account.",
    startMfaSetup: "Start MFA setup",
    preparing: "Preparing...",
    scanQrCode: "1. Scan the QR code",
    scanQrDesc: "Use Google Authenticator, 1Password, Authy, or another TOTP app.",
    manualSetupSecret: "Manual setup secret",
    confirmSixDigit: "2. Confirm with a 6-digit code",
    confirming: "Confirming...",
    disableMfa: "Disable MFA",
    disableMfaDesc: "Enter your password and either a TOTP code or an unused backup code.",
    totpOrBackupCode: "TOTP or backup code",
    disabling: "Disabling...",
    backupCodes: "Backup Codes",
    backupCodesDesc: "Each code can be used once. Store them offline in a secure place.",
    regenerateBackupCodes: "Regenerate backup codes",
    generating: "Generating...",
    confirmCurrentCode: "Confirm with your current 6-digit code",
    currentSixDigitCode: "Current 6-digit code",
    codesDisplayedOnce: "These codes are displayed once. Save them before leaving this page.",
    copyBackupCodes: "Copy backup codes",
    downloadBackupCodes: "Download backup codes",
    noBackupCodesDisplayed: "No backup codes are currently displayed.",

    // Reports
    revenue: "Revenue",
    count: "Count",
    daily: "Daily",
    monthly: "Monthly",
    reportsTitle: "Reports",
    financialAnalytics: "Financial analytics, charts and statistics",
    statistics: "Statistics",
    avgAmount: "Avg. Amount",
    completed: "Completed",
    revenueOverTime: "Revenue over time",
    dailyRevenueCount: "Daily revenue and transaction count",
    noDataForRange: "No data for selected range",
    amountByMethod: "Amount by Method",
    transactionDetails: "Transaction Details",
    eodDetails: "EOD Details",
    eodTrend: "End of Day Trend",
    dailyFinancialPerf: "Daily financial performance",
    eodId: "EOD ID",
    totalTx: "Total Tx",
    success: "Success",
    avgTx: "Avg Tx",
    vsPrevDay: "vs Prev Day",
    noRecordsMatch: "No records match filters",
    avgDailyRevenue: "Avg Daily Revenue",
    totalFailed: "Total Failed",
    daysReported: "Days Reported",
    bestPerformingDay: "Best performing day",
    weakestDay: "Weakest day",
    weekdayVsWeekend: "Weekday vs Weekend",
    weekdaysHigher: "Weekdays higher",
    weekendsHigher: "Weekends higher",
    avgRevByDayOfWeek: "Average Daily Revenue by Day of Week",
    avgTxByDayOfWeek: "Avg Transactions by Day of Week",
    failureRateByDay: "Failure Rate by Day of Week",
    monthlyRevenueTrend: "Monthly Revenue Trend",
    dayOfWeekBreakdown: "Day of Week Breakdown",
    avgRevenue: "Avg Revenue",
    avgTransactions: "Avg Transactions",
    failureRate: "Failure Rate",
    vsBestDay: "vs. Best Day",
    sampleDays: "Sample Days",
    searchIdCustomer: "Search ID, customer, location...",
    searchEodId: "Search EOD ID or date...",
    from: "From",
    to: "To",

    // End of Day
    dailySummaries: "Daily transaction summaries with day-over-day performance",
    missingEod: "Missing End of Day report",
    noEodRecorded: "No EOD was recorded for this date.",
    dismissAlert: "Dismiss alert",
    successPct: "% success rate",
    failurePct: "% failure rate",
    searchEod: "Search by EOD ID or date...",
    dateRange: "Date range",
    allDates: "All Dates",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    thisMonth: "This Month",
    performance: "Performance",
    lowFailure: "Low Failure (≤7%)",
    highFailure: "High Failure (>7%)",
    allCustomers: "All Customers",
    allLocations: "All Locations",
    eodReports: "End of Day Reports",
    reportsArrows: "reports — arrows show change vs previous day",
    vsDay1: "vs Day -1",
    noReportsMatch: "No reports match your filters",

    // Reconciliation
    matchVerify: "Match and verify transactions against expected records",
    matched: "Matched",
    matchRate: "% match rate",
    unmatched: "Unmatched",
    requiresAttention: "Requires attention",
    awaitingConfirmation: "Awaiting confirmation",
    totalDiscrepancy: "Total Discrepancy",
    acrossRecords: "Across records",
    searchReconciliation: "Search by ID, transaction ID or terminal...",
    allStatusesRec: "All Statuses",
    allTerminalsRec: "All Terminals",
    reconciliationRecords: "Reconciliation Records",
    recordsFound: "records found",
    recId: "Rec. ID",
    transactionId2: "Transaction ID",
    expected: "Expected",
    actual: "Actual",
    difference: "Difference",
    noRecordsMatchFilters: "No records match your filters",

    // Invoices
    invoiceManagement: "Invoice Management",
    createManageInvoices: "Create, manage and track invoices with PDF export",
    createInvoice: "Create Invoice",
    totalInvoiced: "Total Invoiced",
    paidAmount: "Paid Amount",
    pendingAmount: "Pending Amount",
    overdueAmount: "Overdue Amount",
    searchInvoice: "Search by invoice number or customer...",
    filterByStatus: "Filter by status",
    allStatusesInv: "All Statuses",
    paid: "Paid",
    overdue: "Overdue",
    thisQuarter: "This Quarter",
    invoiceList: "Invoice List",
    invoicesFound: "invoices found",
    invoiceNum: "Invoice #",
    dueDate: "Due Date",
    downloadPdf: "Download PDF",
    sendReminder: "Send Reminder",
    generatingPdf: "Generating PDF",
  },
  fr: {
    // Nav
    dashboard: "Tableau de bord",
    customers: "Clients",
    spAdmins: "SP Admins",
    transactions: "Transactions",
    terminals: "Terminaux",
    reports: "Rapports",
    reconciliation: "Réconciliation",
    endOfDay: "Fin de journée",
    invoices: "Factures",

    // Common
    search: "Rechercher",
    filter: "Filtrer",
    status: "Statut",
    actions: "Actions",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    view: "Voir",
    add: "Ajouter",
    create: "Créer",
    loading: "Chargement...",
    noData: "Aucune donnée",
    all: "Tous",
    active: "Actif",
    inactive: "Inactif",
    date: "Date",
    amount: "Montant",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    address: "Adresse",
    total: "Total",
    export: "Exporter",
    close: "Fermer",
    back: "Retour",
    confirm: "Confirmer",
    saving: "Enregistrement...",
    deleting: "Suppression...",
    creating: "Création...",
    refresh: "Actualiser",
    tryAgain: "Réessayer",
    clearFilters: "Effacer les filtres",
    viewDetails: "Voir les détails",
    saveChanges: "Enregistrer",
    exportCsv: "Exporter CSV",
    exportReport: "Exporter le rapport",
    show: "Afficher",
    hide: "Masquer",
    type: "Type",
    role: "Rôle",
    created: "Créé",
    currency: "Devise",
    online: "En ligne",
    offline: "Hors ligne",
    enabled: "Activé",
    disabled: "Désactivé",

    // Dashboard
    totalRevenue: "Revenus totaux",
    totalTransactions: "Transactions totales",
    successRate: "Taux de succès",
    activeTerminals: "Terminaux actifs",
    recentActivity: "Activité récente",
    overview: "Vue d'ensemble",
    paymentDashboard: "Tableau de bord paiements",
    welcomeBack: "Bienvenue",
    hotelPaymentOverview: "Voici l'aperçu des paiements de votre hôtel.",
    todayRevenue: "Revenus du jour",
    comparedToYesterday: "Par rapport à hier",
    monthToDate: "Mois en cours",
    thisMonthTotal: "Total du mois",
    avgTransaction: "Transaction moyenne",
    perTransaction: "Par transaction",
    failedTransactions: "Transactions échouées",
    inValue: "en valeur",
    revenueTrend: "Tendance des revenus (7 derniers jours)",
    dailyRevenueVolume: "Revenus journaliers et volume de transactions",
    paymentMethods: "Moyens de paiement",
    distributionByCard: "Répartition par carte et portefeuilles numériques",
    performanceByLocation: "Performance par emplacement",
    transactionVolumeByLocation: "Volume et revenus par emplacement d'hôtel",

    // Transactions
    reference: "Référence",
    paymentMethod: "Moyen de paiement",
    customer: "Client",
    fulfilled: "Réussi",
    failed: "Échoué",
    pending: "En attente",
    refunded: "Remboursé",
    transactionList: "Liste des transactions",
    transactionsFound: "transactions trouvées",
    noTransactionsFound: "Aucune transaction trouvée",
    noTransactionsMatchFilters: "Aucune transaction ne correspond aux filtres",
    loadingTransactions: "Chargement des transactions...",
    transactionId: "ID Transaction",
    dateTime: "Date & Heure",
    allStatuses: "Tous les statuts",
    allMethods: "Tous les moyens",

    // Terminals
    serialNumber: "Numéro de série",
    location: "Emplacement",
    model: "Modèle",
    lastSeen: "Dernière activité",
    terminalManagement: "Gestion des terminaux",
    monitorTerminals: "Surveiller et gérer tous les terminaux de paiement connectés",
    addTerminal: "Ajouter un terminal",
    totalTerminals: "Terminaux totaux",
    acrossAllLocations: "Sur tous les emplacements",
    onlineTerminals: "Terminaux en ligne",
    currentlyActive: "Actuellement actifs",
    totalTransactionsToday: "Transactions du jour",
    acrossAllTerminals: "Sur tous les terminaux",
    terminalsFound: "terminal(s) trouvé(s)",
    terminalId: "ID Terminal",
    todayTransactions: "Transactions du jour",
    terminalTodayRevenue: "Revenus du jour",
    searchTerminal: "Rechercher par ID, nom ou emplacement...",

    // Customers
    properties: "Propriétés",
    users: "Utilisateurs",
    addCustomer: "Ajouter un client",
    editCustomer: "Modifier le client",
    deleteCustomer: "Supprimer le client",
    manageCustomers: "Gérer tous les clients, leurs propriétés et utilisateurs",
    totalCustomers: "Total clients",
    totalProperties: "Total propriétés",
    totalUsers: "Total utilisateurs",
    customerList: "Liste des clients",
    customersFound: "clients trouvés",
    noCustomersYet: "Aucun client pour l'instant. Créez le premier !",
    noCustomersMatchFilters: "Aucun client ne correspond aux filtres.",
    searchCustomer: "Rechercher par nom ou email...",
    newCustomer: "Nouveau client",
    createCustomer: "Créer le client",
    deleteCustomerConfirm: "Êtes-vous sûr de vouloir supprimer",
    deleteCustomerWarning: "Cela supprimera également toutes leurs propriétés et utilisateurs. Cette action est irréversible.",
    customerInformation: "Informations client",
    addCustomerDesc: "Ajouter un nouveau client à la plateforme",
    updateCustomerDesc: "Mettre à jour les informations du client",

    // Customer Detail
    backToCustomers: "Retour aux clients",
    addProperty: "Ajouter une propriété",
    editProperty: "Modifier la propriété",
    deleteProperty: "Supprimer la propriété",
    noPropertiesYet: "Aucune propriété pour l'instant. Ajoutez la première !",
    addUser: "Ajouter un utilisateur",
    editUser: "Modifier l'utilisateur",
    deleteUser: "Supprimer l'utilisateur",
    noUsersYet: "Aucun utilisateur pour l'instant. Ajoutez le premier !",
    propertiesRoles: "Propriétés & Rôles",
    selectPropertiesDesc: "Sélectionnez les propriétés auxquelles cet utilisateur peut accéder et définissez son rôle pour chacune.",
    noPropertiesForUser: "Aucune propriété pour l'instant. Ajoutez d'abord une propriété.",
    fullName: "Nom complet",
    temporaryPassword: "Mot de passe temporaire",
    passwordMinChars: "Mot de passe * (min 8 caractères)",

    // Auth
    login: "Connexion",
    logout: "Déconnexion",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    mfaWarning: "Le MFA est désactivé sur votre compte. Activez-le pour plus de sécurité.",
    enableMfa: "Activer le MFA",
    backToSignIn: "Retour à la connexion",
    resetPassword: "Réinitialiser le mot de passe",
    forgotPasswordTitle: "Mot de passe oublié",
    forgotPasswordDesc: "Nous enverrons un lien de réinitialisation à votre adresse email.",
    sendResetLink: "Envoyer le lien",
    sending: "Envoi...",
    resetLinkSent: "Si un compte avec cet email existe, un lien de réinitialisation a été envoyé. Vérifiez votre boîte de réception.",
    createNewPassword: "Créer un nouveau mot de passe",
    chooseStrongPassword: "Choisissez un mot de passe fort pour sécuriser votre compte.",
    resetPasswordTitle: "Réinitialisation du mot de passe",
    enterNewPasswordBelow: "Entrez votre nouveau mot de passe ci-dessous.",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    resetting: "Réinitialisation...",
    passwordResetSuccess: "Votre mot de passe a été réinitialisé avec succès.",
    invalidResetLink: "Lien de réinitialisation invalide.",
    missingToken: "Ce lien ne contient pas de jeton. Veuillez demander une nouvelle réinitialisation.",
    requestNewLink: "Demander un nouveau lien",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",
    passwordMinLength: "Le mot de passe doit comporter au moins 8 caractères.",
    invalidToken: "Jeton invalide ou manquant. Veuillez demander un nouveau lien.",
    resetLinkExpired: "Échec de la réinitialisation. Le lien a peut-être expiré.",
    editProfile: "Modifier le profil",
    signOut: "Se déconnecter",

    // Profile
    profile: "Profil",
    manageAccountSettings: "Gérez les paramètres et préférences de votre compte",
    personalInformation: "Informations personnelles",
    accountSettings: "Paramètres du compte",
    changePassword: "Changer le mot de passe",
    twoFactorAuth: "Authentification à deux facteurs",
    notificationPreferences: "Préférences de notification",
    activitySummary: "Résumé d'activité",
    lastLogin: "Dernière connexion",
    sessionsActive: "Sessions actives",
    accountStatus: "Statut du compte",
    currentPassword: "Mot de passe actuel",
    enterCurrentPassword: "Entrez le mot de passe actuel",
    minEightChars: "Min. 8 caractères",
    repeatNewPassword: "Répétez le nouveau mot de passe",
    newPasswordsNoMatch: "Les nouveaux mots de passe ne correspondent pas.",
    newPasswordMinLength: "Le nouveau mot de passe doit comporter au moins 8 caractères.",
    passwordChanged: "Mot de passe modifié",
    passwordUpdatedSuccess: "Votre mot de passe a été mis à jour avec succès.",

    // MFA
    mfaTitle: "Authentification multi-facteurs",
    mfaDesc: "Protégez votre compte avec une application d'authentification et des codes de secours à usage unique.",
    backToProfile: "Retour au profil",
    loadingMfaStatus: "Chargement du statut MFA...",
    currentProtection: "Protection actuelle",
    mfaEnabled: "MFA activé",
    mfaDisabled: "MFA désactivé",
    backupCodesRemaining: "Codes de secours restants",
    enableMfaProtection: "Activer la protection MFA",
    enableMfaDesc: "Ajoutez une application d'authentification et des codes de secours pour protéger ce compte.",
    startMfaSetup: "Démarrer la configuration MFA",
    preparing: "Préparation...",
    scanQrCode: "1. Scannez le QR code",
    scanQrDesc: "Utilisez Google Authenticator, 1Password, Authy ou une autre application TOTP.",
    manualSetupSecret: "Code de configuration manuelle",
    confirmSixDigit: "2. Confirmez avec un code à 6 chiffres",
    confirming: "Confirmation...",
    disableMfa: "Désactiver le MFA",
    disableMfaDesc: "Entrez votre mot de passe et un code TOTP ou un code de secours non utilisé.",
    totpOrBackupCode: "Code TOTP ou code de secours",
    disabling: "Désactivation...",
    backupCodes: "Codes de secours",
    backupCodesDesc: "Chaque code ne peut être utilisé qu'une seule fois. Conservez-les hors ligne dans un endroit sûr.",
    regenerateBackupCodes: "Régénérer les codes de secours",
    generating: "Génération...",
    confirmCurrentCode: "Confirmez avec votre code actuel à 6 chiffres",
    currentSixDigitCode: "Code actuel à 6 chiffres",
    codesDisplayedOnce: "Ces codes ne sont affichés qu'une seule fois. Sauvegardez-les avant de quitter cette page.",
    copyBackupCodes: "Copier les codes de secours",
    downloadBackupCodes: "Télécharger les codes de secours",
    noBackupCodesDisplayed: "Aucun code de secours n'est actuellement affiché.",

    // Reports
    revenue: "Revenus",
    count: "Nombre",
    daily: "Journalier",
    monthly: "Mensuel",
    reportsTitle: "Rapports",
    financialAnalytics: "Analyses financières, graphiques et statistiques",
    statistics: "Statistiques",
    avgAmount: "Montant moy.",
    completed: "Complété",
    revenueOverTime: "Revenus dans le temps",
    dailyRevenueCount: "Revenus journaliers et nombre de transactions",
    noDataForRange: "Aucune donnée pour la période sélectionnée",
    amountByMethod: "Montant par moyen",
    transactionDetails: "Détails des transactions",
    eodDetails: "Détails fin de journée",
    eodTrend: "Tendance fin de journée",
    dailyFinancialPerf: "Performance financière journalière",
    eodId: "ID FdJ",
    totalTx: "Total Tx",
    success: "Succès",
    avgTx: "Moy. Tx",
    vsPrevDay: "vs Jour préc.",
    noRecordsMatch: "Aucun enregistrement ne correspond aux filtres",
    avgDailyRevenue: "Revenus journaliers moy.",
    totalFailed: "Total échoués",
    daysReported: "Jours rapportés",
    bestPerformingDay: "Meilleur jour",
    weakestDay: "Jour le plus faible",
    weekdayVsWeekend: "Semaine vs Week-end",
    weekdaysHigher: "Jours de semaine plus élevés",
    weekendsHigher: "Week-ends plus élevés",
    avgRevByDayOfWeek: "Revenus journaliers moyens par jour de la semaine",
    avgTxByDayOfWeek: "Transactions moyennes par jour de la semaine",
    failureRateByDay: "Taux d'échec par jour de la semaine",
    monthlyRevenueTrend: "Tendance des revenus mensuels",
    dayOfWeekBreakdown: "Détail par jour de la semaine",
    avgRevenue: "Revenu moy.",
    avgTransactions: "Transactions moy.",
    failureRate: "Taux d'échec",
    vsBestDay: "vs. Meilleur jour",
    sampleDays: "Jours échantillon",
    searchIdCustomer: "Rechercher ID, client, emplacement...",
    searchEodId: "Rechercher ID FdJ ou date...",
    from: "De",
    to: "À",

    // End of Day
    dailySummaries: "Résumés journaliers avec performance jour après jour",
    missingEod: "Rapport fin de journée manquant",
    noEodRecorded: "Aucun FdJ n'a été enregistré pour cette date.",
    dismissAlert: "Ignorer l'alerte",
    successPct: "% taux de succès",
    failurePct: "% taux d'échec",
    searchEod: "Rechercher par ID FdJ ou date...",
    dateRange: "Période",
    allDates: "Toutes les dates",
    today: "Aujourd'hui",
    yesterday: "Hier",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois",
    performance: "Performance",
    lowFailure: "Faible échec (≤7%)",
    highFailure: "Échec élevé (>7%)",
    allCustomers: "Tous les clients",
    allLocations: "Toutes les locations",
    eodReports: "Rapports fin de journée",
    reportsArrows: "rapports — les flèches indiquent le changement vs jour précédent",
    vsDay1: "vs Jour -1",
    noReportsMatch: "Aucun rapport ne correspond aux filtres",

    // Reconciliation
    matchVerify: "Correspondre et vérifier les transactions par rapport aux enregistrements attendus",
    matched: "Correspondant",
    matchRate: "% taux de correspondance",
    unmatched: "Non correspondant",
    requiresAttention: "Nécessite une attention",
    awaitingConfirmation: "En attente de confirmation",
    totalDiscrepancy: "Écart total",
    acrossRecords: "Sur tous les enregistrements",
    searchReconciliation: "Rechercher par ID, ID de transaction ou terminal...",
    allStatusesRec: "Tous les statuts",
    allTerminalsRec: "Tous les terminaux",
    reconciliationRecords: "Enregistrements de réconciliation",
    recordsFound: "enregistrements trouvés",
    recId: "ID Réc.",
    transactionId2: "ID Transaction",
    expected: "Attendu",
    actual: "Réel",
    difference: "Différence",
    noRecordsMatchFilters: "Aucun enregistrement ne correspond aux filtres",

    // Invoices
    invoiceManagement: "Gestion des factures",
    createManageInvoices: "Créer, gérer et suivre les factures avec export PDF",
    createInvoice: "Créer une facture",
    totalInvoiced: "Total facturé",
    paidAmount: "Montant payé",
    pendingAmount: "Montant en attente",
    overdueAmount: "Montant en retard",
    searchInvoice: "Rechercher par numéro de facture ou client...",
    filterByStatus: "Filtrer par statut",
    allStatusesInv: "Tous les statuts",
    paid: "Payé",
    overdue: "En retard",
    thisQuarter: "Ce trimestre",
    invoiceList: "Liste des factures",
    invoicesFound: "factures trouvées",
    invoiceNum: "Facture n°",
    dueDate: "Échéance",
    downloadPdf: "Télécharger PDF",
    sendReminder: "Envoyer un rappel",
    generatingPdf: "Génération du PDF",
  },
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem("sp_lang") as Lang) || "fr"
  );

  const setLang = (l: Lang) => {
    localStorage.setItem("sp_lang", l);
    setLangState(l);
    // Persist to backend if authenticated
    if (AuthService.isAuthenticated()) {
      const token = AuthService.getAccessToken();
      fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:4000/api'}/auth/lang`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ lang: l }),
      }).catch(() => {});
    }
  };

  const t = (key: TranslationKey): string => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
