export const PERMISSIONS = {
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  VIEW_EOD: "VIEW_EOD",
  USE_VIRTUAL_TERMINAL: "USE_VIRTUAL_TERMINAL",
  MANAGE_TERMINALS: "MANAGE_TERMINALS"
}