import { ROLES } from "./roles"
import { PERMISSIONS } from "./permissions"

   

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),
  sp_admin: Object.values(PERMISSIONS),

  [ROLES.HOTEL_MANAGER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_EOD,
    PERMISSIONS.USE_VIRTUAL_TERMINAL,
    PERMISSIONS.MANAGE_TERMINALS
  ],

  [ROLES.FRONT_OFFICE_MANAGER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_EOD,
    PERMISSIONS.USE_VIRTUAL_TERMINAL
  ],

  [ROLES.FRONT_OFFICE_OPERATOR]: [
    PERMISSIONS.VIEW_TRANSACTIONS
  ]
}